# Generated by Django 3.2.25 on 2025-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20251122_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.IngredientInRecipe', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
