# Generated by Django 3.2.3 on 2025-11-17 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251106_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Уникальное имя пользователя (никнейм).', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный никнейм: допустимы только буквы, цифры и символы @/./+/-/_', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
